### PR TITLE
Added dutch translation

### PR DESCRIPTION
**Pull request by dtaalbers**

### CODE REVIEW

**Comment by dtaalbers** [comment]
Oh wow, I've never noticed your reply. Some credits will be nice if it is not to much trouble!

**Comment by KingYes** [comment]
You can see what I left in our readme.. If you want any other credit, let's me know !

**Comment by dtaalbers** [comment]
The credits in the readme are fine! Only its redirecting to the wrong website though. It should be http://www.dtaalbers,com.

**Comment by KingYes** [comment]
Done.
Thanks.

**Pull request merged**
